# https://github.com/awslabs/serverless-application-model/blob/develop/versions/2016-10-31.md
# Indentation needs to be set with spaces, because YAML...
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: API endpoint for user achievements

Globals:
    Function:
        Environment:
            Variables:
                SQS_URL: !Ref SaveAchievementsQueue

Resources:
    SaveAchievementsQueue:
        Type: AWS::SQS::Queue
        Properties:
            QueueName: deferred-save-achievements-queue
            VisibilityTimeout: 601
    RetrieveAchievementsFunction2:
        Type: AWS::Serverless::Function
        Properties:
            Handler: retrieve-achievements.default
            Runtime: nodejs16.x
            CodeUri: ./dist/retrieve-achievements
            Timeout: 29
            MemorySize: 128
            Layers:
                - !Sub "arn:aws:lambda:${AWS::Region}:580247275435:layer:LambdaInsightsExtension:14"
            Policies:
                - AWSLambdaVPCAccessExecutionRole
                - AmazonSESFullAccess
                - AmazonSQSFullAccess
                - SecretsManagerReadWrite
                - arn:aws:iam::aws:policy/CloudWatchLambdaInsightsExecutionRolePolicy
                # - arn:aws:iam::478062583808:policy/CloudWatchPolicyForLambda # See https://stackoverflow.com/questions/51166504/disable-cloudwatch-to-monitor-logs-for-lambda-function
            Tags:
                LambdaName: api-retrieve-achievements-2
            AutoPublishAlias: live
            FunctionUrlConfig:
                AuthType: NONE
    StartSaveAchievementsFunction2:
        Type: AWS::Serverless::Function
        Properties:
            Handler: start-save-achievements.default
            Runtime: nodejs16.x
            CodeUri: ./dist/start-save-achievements
            Timeout: 3
            MemorySize: 128
            Policies:
                - AWSLambdaVPCAccessExecutionRole
                - AmazonSESFullAccess
                - AmazonSQSFullAccess
                - SecretsManagerReadWrite
                # - arn:aws:iam::478062583808:policy/CloudWatchPolicyForLambda # See https://stackoverflow.com/questions/51166504/disable-cloudwatch-to-monitor-logs-for-lambda-function
            Tags:
                LambdaName: api-start-save-achievements-2
            AutoPublishAlias: live
            FunctionUrlConfig:
                AuthType: NONE
    ProcessSaveAchievementsFunction:
        Type: AWS::Serverless::Function
        Properties:
            Handler: process-save-achievements.default
            Runtime: nodejs16.x
            CodeUri: ./dist/process-save-achievements
            MemorySize: 128
            ReservedConcurrentExecutions: 5
            Layers:
                - !Sub "arn:aws:lambda:${AWS::Region}:580247275435:layer:LambdaInsightsExtension:14"
            Policies:
                - AWSLambdaVPCAccessExecutionRole
                - SecretsManagerReadWrite
                - AmazonSESFullAccess
                - AmazonSQSFullAccess
                - arn:aws:iam::aws:policy/CloudWatchLambdaInsightsExecutionRolePolicy
                # - arn:aws:iam::478062583808:policy/CloudWatchPolicyForLambda # See https://stackoverflow.com/questions/51166504/disable-cloudwatch-to-monitor-logs-for-lambda-function
            Tags:
                LambdaName: process-save-achievements
            Timeout: 60
            Events:
                SQSEvent:
                    Type: SQS
                    Properties:
                        Queue: !GetAtt SaveAchievementsQueue.Arn
                        # BatchSize: 1
